### PR TITLE
Fix: handle puppeteer result format for v23

### PR DESCRIPTION
**Pull request by lorenzk**
Fixes https://github.com/Studiosity/grover/issues/252

I just took @taylorthurlow's fix and made it work with older versions of puppeteer. Tested locally with puppeteer 23 and 22.

### CODE REVIEW

**Review by andrew-smith-nz — APPROVED** [review]
Made this same change myself manually before finding this PR.  Can confirm it works.

**Review by rud — APPROVED** [review]
Awesome! Would it be possible to add a testcase to verify the behaviour?

**Comment by lorenzk** [comment]
I took a look at the specs but did not see a way to manipulate puppeteers output. I believe the real test is running `processor_spec.rb` against puppeteer 23.x, so I added that to the test matrix.

If you cherry-pick just the test matrix change to `main`, you should see it red and then green on this branch.

**Comment by abrom** [comment]
Thanks for the PR @lorenzk 👍 

Note i've patched this "upstream" in the `processor.tsx` script instead to keep the Ruby interface unified (see #258)

The fix has been released in [v1.1.10](https://rubygems.org/gems/grover/versions/1.1.10)

**Pull request closed without merging**
