### PR TITLE
Extend "Running on Heroku" readme section.

### PR DESCRIPTION
**Pull request by pvaldesoiro**
Added a step to add Puppeteer to package.json, and a warning about incompatibility with Heroku and certain versions of Puppeteer.

### CODE REVIEW

**Comment by abrom** [comment]
Hi @pvaldesoiro 

Thank you for the PR, although per my comment in the issue you raised about this https://github.com/Studiosity/grover/issues/166#issuecomment-1313378539 I suspect there is likely a better way to keep things moving forward rather than requiring puppeteer be pegged at a specific version. I'd appreciate your thoughts and any feedback you can give me on the above tagged comment!

**Comment by pvaldesoiro** [comment]
Hello @abrom, sorry for the late reply.

I think you are right. Adding a warning informing the user about adding `.puppeteerrc.cjs` with the cache config in case they want to make Grover work with puppeteer v19.x would be a much better option than advising to keep puppeteer stuck at an old version. I will update the PR if you are fine with it. But anyway, if you have any other suggestions I would have no problem with trying an alternative approach; or you prefer to keep the readme as it is right now and address the issue in future versions, I can just close the PR.

**Comment by abrom** [comment]
Sounds great, updating the README to include details about the config change feels like the best option. Thanks @pvaldesoiro 👍

**Comment by abrom** [comment]
Good to close this now that #169 is merged?

**Comment by pvaldesoiro** [comment]
@abrom Yes. Closed.

**Pull request closed without merging**
